### ISSUE TITLE
Does this library restrict the version of Django?

### ISSUE THREAD

**Issue by begriffs** [citusdata/django-multitenant#1] opened 2017-07-17 22:34 UTC
I added `django_multitenant` to the requirements.txt on an existing Django 1.11 project. However running `pip install -r requirements.txt` then uninstalls Django and downgrades it to 1.10:

```
Installing collected packages: Django, django-multitenant
  Found existing installation: Django 1.11
    Uninstalling Django-1.11:
      Successfully uninstalled Django-1.11
  Running setup.py install for django-multitenant ... done
Successfully installed Django-1.10 django-multitenant-0.3
```

Not sure if the dependencies of this library caused that to happen, and recording an issue just in case.

**Comment by saicitus** [comment] 2017-10-31 21:40
@jasonmp85 Any thoughts on why the above is happening.  Could it be because of the `find_packages()` in the `setup.py`

**Comment by jasonmp85** [comment] 2017-10-31 21:54
Gah, I swore we debugged and figured this out a while back; I don't remember anymore, though…

**Comment by saicitus** [comment] 2017-11-06 22:44
Hey @begriffs, just FYI, I tested this with the latest library release and couldn't reproduce this issue.
```
#Did this with django 1.11 already installed.
pip install django-multitenant
Collecting django-multitenant
Installing collected packages: django-multitenant
Successfully installed django-multitenant-1.0.1
```
Could it be because of your apps [requirements.txt](https://github.com/citusdata/django_multitenant/blob/master/requirements.txt) rather than the django-multitenant library restricting the django version?

**Comment by saicitus** [comment] 2017-11-09 23:25
Tested and hence closing the issue.

**Closed by saicitus** 2017-11-09 23:25 UTC
